name: Bug Report
description: Report a bug in the SDK.
title: "[Bug Report]: "
labels: ["Bug Report", "SDK"]
body:
  - type: markdown
    attributes:
      value: "## Bug Report\nPlease fill out the following information to help us understand and fix the issue."
  - type: textarea
    attributes:
      label: "Bug Description"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "Describe the bug here..."
    validations:
      required: true
  - type: input
    attributes:
      label: "SDK Version"
      description: "Which version of the SDK does this issue affect?"
      placeholder: "Enter the SDK version here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the bug."
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behaviour"
      description: "Describe what you expected to happen."
      placeholder: "Explain here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Attach screenshots here..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "Add context here..."
    validations:
      required: false
