name: Feature Request
description: Suggest a new feature for the SDK.
title: "[Feature Request]: "
labels: ["Feature Request", "SDK"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request\nPlease provide a detailed description of the feature you are proposing."
  - type: textarea
    attributes:
      label: "Feature Description"
      description: "Describe the feature you'd like to add to the SDK."
      placeholder: "Detail the feature here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Benefit to the SDK"
      description: "Explain how this feature would benefit the SDK and its users."
      placeholder: "Explain the benefit here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Possible Implementation"
      description: "Do you have ideas on how this feature should be implemented?"
      placeholder: "Describe any implementation ideas here..."
    validations:
      required: false
