name: Wiki Update
description: Request updates or additions to the Wiki.
title: "[Wiki Update]: "
labels: ["Wiki"]
body:
  - type: markdown
    attributes:
      value: "## Wiki Content Update Request\nPlease fill out the following information to help us update the Wiki content effectively."
  - type: textarea
    attributes:
      label: "What content do you want to update or add?"
      description: "Provide a clear and concise description of what content needs to be updated or added."
      placeholder: "Detail the content here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Why is this update or addition necessary?"
      description: "Explain the relevance and importance of this update or addition."
      placeholder: "Explain here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Proposed changes or content"
      description: "Please describe your proposed changes or the content you wish to add."
      placeholder: "Detail your proposal..."
    validations:
      required: true
