name: Wiki New Page
description: Propose the addition of a new page to the Wiki.
title: "[Wiki New Page]: "
labels: ["Wiki"]
body:
  - type: markdown
    attributes:
      value: "## Wiki New Page Proposal\nPlease provide detailed information about the new page you are proposing."
  - type: textarea
    attributes:
      label: "Title of the new page"
      description: "What is the title of the page you are proposing?"
      placeholder: "Enter the title here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Purpose of the new page"
      description: "Explain the purpose of this new page and why it is necessary."
      placeholder: "Explain the purpose here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Suggested content outline"
      description: "Provide a brief outline of the content you propose for this page."
      placeholder: "Outline the content here..."
    validations:
      required: true
